
modLoader="javafml"
loaderVersion="[31,)"

issueTrackerURL="https://github.com/TyrellPlayz/ZLib/issues"

[[mods]]
modId="zlib"
version="0.1.0"
displayName="ZLib"
updateJSONURL="https://raw.githubusercontent.com/TyrellPlayz/ZLib/master/update.json"
displayURL="https://github.com/TyrellPlayz/ZLib"
logoFile="examplemod.png"
credits=""
authors="TyrellPlayz"
description="The mod libray used by all mods created by TyrellPlayz"

[[dependencies.zLib]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.zLib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
