
modLoader="javafml"
loaderVersion="[28,)"

issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="zlib"
version="0.1.0"
displayName="ZLib"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits=""
authors="TyrellPlayz"
description="The mod libray used by all mods created by TyrellPlayz"

[[dependencies.zLib]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.zLib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
